name: Run ruff

on:
  pull_request:
    branches: ['main']

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run ruff
      run: |
        ruff .

    - name: Upload ruff result if failed
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ruff-report
        path: ruff.log

    - name: Fail if ruff fails
      if: failure()
      run: exit 1