[settings]
url_login = "https://login.altiplan.dk/webmodul/"
url_schedule = "https://login.altiplan.dk/webmodul/ugeplan/"
path_html_output = "data/html/altiplan_ugeplan.html"
NUM_WEEKDAYS = 7
ERGO_AKTIVITETER = 65 
BARN_SYG_AND_FERIE = [74, 75]
