[settings]
save_html = true
run_headless = true
run_selenium_regardless = true

url_login = "https://login.altiplan.dk/webmodul/"
url_schedule = "https://login.altiplan.dk/webmodul/ugeplan/"
path_html_output = "data/html/altiplan_ugeplan.html"
js_ID_department = "Afdeling-form"
js_ID_username = "Brugernavn-form"
js_ID_password = "Password-form"
js_XPATH_unique_afterlogin_elem = "//*[@id='dashboard-container']/div[2]"
NUM_WEEKDAYS = 7
skippable_funcs = ["ERGO aktiviteter", "Syg/barns syg", "Kursus/Ferie/Fri"]  # These might be fragile depending on naming
WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
valid_monikers = ["elev", "stud"]
